### ISSUE TITLE
开机背光问题

### ISSUE THREAD

**Issue by docee** [Sulisong/Lenovo-Y9000X-Hackintosh#1]
升级到macOS 13.4就出现了LED背光无法开启的问题（大概5-10分钟会自动恢复）。

我也尝试了和你一样的做法，启用 -igfxblr 。但是并不起作用啊，关机后再启动还是可能继续会出现这个问题。

**Comment by docee** [comment]
https://github.com/acidanthera/bugtracker/issues/2241
这个问题应该是13.4的问题，据说13.5已经修复。

**Comment by Sulisong** [comment]
这样子啊，我尝试了-igfxblr解决了，后面升级了13.5

**Comment by docee** [comment]
> 这样子啊，我尝试了-igfxblr解决了，后面升级了13.5

就怕beta版本问题更多😶。。。。
